import Head from 'next/head';
import Footer from "../components/Footer";
import Navbar from "../components/Navbar"
import Cards from "../components/Cards";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Haris Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/*Navbar*/}
        <Navbar />

      {/*Catagories*/}

      {/*Cards*/}
      <div className="mx-12 px-3">
      <Cards/>
      </div>
      {/*Footer*/}
       <Footer />
    </div>
  )
}
